### ISSUE TITLE
依赖库之后app_name怎么变成了jlog！？

### ISSUE THREAD

**Issue by MIkeeJY** [JiongBull/jlog#1]
我自己的app name 应用名在string里都没问题啊 就是加了这个依赖库自己就变了 去除就没事。。

**Comment by MIkeeJY** [comment]
源码里面的res 貌似直接用gradle 依赖会跟本地的res 里面的string冲突！

**Comment by MIkeeJY** [comment]
已经导出jar包- -！

**Comment by CoenQian** [comment]
兄弟，你是`compile 'com.jiongbull:jlog:1.0.2'` 这样引用的么，我这样引用的没发现问题。没看明白您的意思，有没有错图截图提供一下啊。

**Comment by MIkeeJY** [comment]
没错是这样引用的 我把你项目的res去掉打成jar包引用就没事了 不然我主工程的 应用名会变成Jlog。。

**Comment by CoenQian** [comment]
明白了，我修改一下。

**Comment by CoenQian** [comment]
@MIkeeJY 麻烦你验证一下，`compile 'com.jiongbull:jlog:1.0.3'`
