### ISSUE TITLE
Settings里面的LogDir

### ISSUE THREAD

**Issue by ihrthk** [JiongBull/jlog#12]
1.希望在Settings可以看到，完成的目录位置
2.默认目录位置不应该放在根目录下，应该放在包名下。
3.考虑总的日志文件大小限制

**Comment by CoenQian** [comment]
1. `Setting.getLogDir()`可以获取日志目录
2. 现在没有用包名当文件目录的啦
3. [jlog-qiniu](https://github.com/JiongBull/jlog-qiniu) 可以定时同步文件到七牛并清除本地日志

**Comment by CoenQian** [comment]
@ihrthk 支持设置日志空间的容量，参考[jlog-storage-disk](https://github.com/JiongBull/jlog-storage-disk)
