### ISSUE TITLE
Eliminate Chinglish expressions...

### ISSUE THREAD

**Issue by ryanhoo** [JiongBull/jlog#14]
**jlog** seems to be a cool project but it's README is filled with Chinese-ish english expressions.

> jlog is an useful log tool for android developers.
> 
> orhanobut's logger, ZhaoKaiQiang's KLog and JakeWharton's timber give me inspiration and reference, thank them for their open source spirit.
> 
> Combining with work experience, i made this libriary.
> 
> Hope you enjoy it. ( ^_^ )

This is my revision for your reference:

> jlog is a useful log tool for android developers which was inspired by these projects:
> - [logger](https://github.com/orhanobut/logger) by orhanobut
> - [KLog](https://github.com/ZhaoKaiQiang/KLog) by ZhaoKaiQiang
> - [timber](https://github.com/JakeWharton/timber) by JakeWharton
> 
> With highly appreciation to the spirit of open source, I started this project from my work experience.

**Comment by CoenQian** [comment]
Thanks for your advice.
