### ISSUE TITLE
日志文件大小如何设置?

### ISSUE THREAD

**Issue by weimianlong** [JiongBull/jlog#15]

**Comment by CoenQian** [comment]
一般来说不重要的日志不要写到文件中，如果有需要，自己可以定制一些清除日志的策略，或者可以使用[jlog-qiniu](https://github.com/JiongBull/jlog-qiniu) ，它定时同步文件到七牛并清除本地日志。

**Comment by weimianlong** [comment]
有什么接口能扩展实现自定义写日志文件策略？比如固定文件大小，循环写覆盖最老的记录等。。

**Comment by CoenQian** [comment]
@weimianlong  支持设置日志空间的容量，参考[jlog-storage-disk](https://github.com/JiongBull/jlog-storage-disk)，也可以实现IStorage接口自己定义策略。
