### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by lxs0226** [JiongBull/jlog#27]
Unable to start receiver com.jiongbull.jlog.receiver.LogReceiver: 
java.lang.IllegalStateException: Not allowed to start service Intent { 
cmp=xxx/com.jiongbull.jlog.service.LogService (has extras) }:
 app is in background uid UidRecord{ee8556d u0a244 RCVR bg:
+1h12m44s87ms idle change:uncached procs:3 seq(0,0,0)}

你好，这是线上的崩溃日志，应该就是静态注册的广播在后台运行的时候拉起服务了，高版本会出现崩溃，这块能做下保护么

**Comment by CoenQian** [comment]
抱歉，这个库已经很久没有维护了，目前精力不足，后面我会上传一个 kotlin 版本的。
