### ISSUE TITLE
希望能够提供修改调用栈深度的方法

### ISSUE THREAD

**Issue by bluzwong** [JiongBull/jlog#6]
如果将JLog.v再一次封装，那么用再一次封装过的方法只会打印封装处的行号。
private static int getStackIndex(@NonNull StackTraceElement[] elements) {
        boolean isChecked = false;
        StackTraceElement element;
        for (int i = 0; i < elements.length; i++) {
            element = elements[i];
            if (LOG_CLASS_NAME.equals(element.getClassName())
                    && LOG_PRINT_METHOD_NAME.equals(element.getMethodName())) {
                isChecked = true;
            }
            if (isChecked) {
                int index = i + 2;
                if (index < elements.length) {
                    return index;
                }
            }
        }
        return -1;
    }
希望可以有修改 int index = i + 2; 硬编码的方法。蟹蟹！

**Comment by CoenQian** [comment]
![](http://7xize8.com1.z0.glb.clouddn.com/jlog_jlog%E7%9A%84%E8%B0%83%E7%94%A8%E6%A0%88%E7%BB%93%E6%9E%84.png)

试一试 

`compile 'com.jiongbull:jlog:1.0.5'`

``` java
JLog.init(this)
    .setPackagedLevel(1); // 封装层级，封装一层就传1
```

**Comment by bluzwong** [comment]
👍👍👍
